[project]
name = "tierpsy-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Christoph Sommer", email = "christoph.sommer@ist.ac.at" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
get_speed = "tierpsy_tools:get_speed"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
